### ISSUE TITLE
Problema na numeração da rede

### ISSUE THREAD

**Issue by Phadina** [jorgealmerio/QEsg#7]
Boa tarde, 

Eu sou aluna da UFPR, estou usando o pluging QESG para fazer traçado de uma rede para o meu trabalho final de curso.
Está dando erro na hora de renomear as redes de coleta: 
ValueError: Null geometry cannot be converted to a polyline. 
Traceback (most recent call last):
  File "C:\Users/phadi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QEsg\QEsg_00Settings.py", line 845, in Rename
    self.RenameClasse.initGui()
  File "C:\Users/phadi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QEsg\QEsg_00Rename.py", line 68, in initGui
    self.CheckPolylines(vl,SilentRun=True)
  File "C:\Users/phadi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QEsg\QEsg_00Rename.py", line 492, in CheckPolylines
    vertices = geom.asPolyline()

2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado terrainsurfaceconvexity para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado terrainsurfacetexture para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado thiessenpolygons para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado thinplatesplinetin para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado thinplatespline para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado thresholdbuffer para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado topofatmospherereflectance para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado topographiccorrection para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado topographicopenness para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado topographicpositionindextpi para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado topographicwetnessindextwi para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado tpibasedlandformclassification para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado transectthroughpolygonshapefile para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado transformfeatures para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado transposerasters para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado triangulation para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado union para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado universalkriging para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado update para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado upslopeanddownslopecurvature para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado upslopearea para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado valleyandridgedetectiontophatapproach para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado valleydepth para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado variogramcloud para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado vectorisingrasterclasses para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado vectorruggednessmeasurevrm para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado vegetationindexdistancebased para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado vegetationindexslopebased para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado verticaldistancetochannelnetwork para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado warpingfeatures para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado waterretentioncapacity para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado watershedbasins para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado windexpositionindex para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado zonalrasterstatistics para o fornecedor saga
2022-11-26T13:59:29     WARNING    Nome do algoritmo duplicado zonalmultipleregressionanalysispointsandpredictorrasters para o fornecedor saga

Poderia me ajudar com o ocorido.

Att..

Phadina.

**Comment by jorgealmerio** [comment]
Bom dia,

Está dando um erro de geometria Nula (ValueError: Null geometry cannot be converted to a polyline).
Tente rodar o algoritmo ‘Corrigir geometrias’ em sua rede. Salve o arquivo corrigido e altere nas configurações do QEsg a rede para esse novo arquivo.

Qualquer coisa me fale.

Abraço,

Jorge
